# Generated by Django 4.2 on 2023-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridview', '0002_notify_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='notication_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='notification_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
